spring:
  datasource:
    platform: postgres
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ask_sandbox_db;MODE=PostgreSQL;IGNORECASE=TRUE;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        SQL: debug

